/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTiposOperadores;

public class App {
  

    public static void main(String[] args) {
        
        
        
        int idade = 0;
        float cotacaoDolar = 5.0f;
        double cotcaoEuro = 6.0d;
        char genero = 'M';
        byte ponto = 0;
        boolean estaCadastrado = false;
        
        String  nome = "Esse é um texto de uma variavel STRING";
    }
}
