/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // comentário de linha
        /*Comentário de bloco  */
        /**Contário de documentação */     
        System.out.println(new App().getGreeting());
        System.out.println("Olá mundo");
        System.out.println("Meu segundo comando de saida");
    }
}
