/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ComandoLeituraGravacao;

import java.util.Scanner;

public class App {
  

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        
        int idade = leitor.nextInt();
        float contacaoDolar = leitor.nextFloat();
        double cotcaoEuro = leitor.nextDouble();
        String nome = leitor.nextLine();
        String codigoRua = leitor.next();
        
        System.out.println("Imprime e Pula linha");
        System.out.print("Imprime e não Pula linha");
    
       
    }
}
